<?php
class Mahasiswa_model extends CI_Model
{
	function __construct()
	{
		parent::__construct();

	}

	function get_by_nim($nim){

		$query=$this->db->query("SELECT NIM,INITCAP(NAMA) NAMA,JK,GOL_DARAH,TINGGI,BERAT,INITCAP(PEKERJAAN) PEKERJAAN,DECODE(STATUS_KAWIN,'B','Belum Kawin','K','Kawin') STATUS_KAWIN,INITCAP(FAK) FAK,INITCAP(PRODI) PRODI,INITCAP(ALAMAT_RUMAH) ALAMAT_RUMAH,RT_RUMAH,INITCAP(DESA_RUMAH) DESA_RUMAH,INITCAP(NM_KEC_RUMAH) NM_KEC_RUMAH,INITCAP(NM_KAB_RUMAH) NM_KAB_RUMAH,INITCAP(NM_PROP_RUMAH) NM_PROP_RUMAH,HP_MHS,INITCAP(ALAMAT_JOGJA) ALAMAT_JOGJA,RT_JOGJA,INITCAP(DESA_JOGJA) DESA_JOGJA,INITCAP(NM_KEC_JOGJA) NM_KEC_JOGJA,INITCAP(NM_KAB_JOGJA) NM_KAB_JOGJA,TELP_MHS,INITCAP(PRESTASI) PRESTASI,INITCAP(TRANSPORTASI) TRANSPORTASI,PATH_FOTO,PATH_SK_DOKTER,PATH_SK_GOLONGAN_DARAH,PATH_SK_CUTI,PATH_SK_TIDAK_HAMIL,SUDAH FROM KKN_MHS WHERE NIM='$nim'");
		return $query;
	}


	function get_member_kelompok_by_nim($nim){
		$query=$this->db->query("
				SELECT A.ID_KELOMPOK, B.NIM, B.FAK ,C.NAMA, C.HP_MHS FROM KKN_DETAIL_KELOMPOK A,KKN_MHS B, D_MAHASISWA C WHERE A.NO=B.NO AND B.NIM=C.NIM AND ID_KELOMPOK =(SELECT ID_KELOMPOK FROM KKN_DETAIL_KELOMPOK WHERE NO =(SELECT NO FROM KKN_MHS WHERE NIM='$nim'))");
		return $query;

	}

	function get_info_kelompok($nim){
		$q=$this->db->query("select DISTINCT A.NAMA_KELOMPOK, D.NM_DOSEN, D.MOBILE, A.RW ,A.DESA, E.NM_KEC, F.NM_KAB FROM KKN_KELOMPOK A, KKN_DETAIL_KELOMPOK B, KKN_MHS C , D_DOSEN D, MD_KEC E, MD_KAB F WHERE A.ID_KELOMPOK=B.ID_KELOMPOK AND C.NO=B.NO AND A.KD_DOSEN=D.KD_DOSEN AND A.KD_KEC=E.KD_KEC AND A.KD_KAB=F.KD_KAB AND C.NIM='$nim'");
		return $q;



	}
	
	function get_sudah_kkn_mhs($nim){
		$query= $this->db->query("select SUDAH FROM KKN_MHS where NIM='$nim'");
		return $query;
	
	}
	
	function get_angkatan_kkn($nim){
		$query= $this->db->query("select  D.ANGKATAN, E.PERIODE, F.TA, E.TANGGAL_MULAI, E.TANGGAL_SELESAI FROM KKN_MHS A, KKN_DETAIL_KELOMPOK B, KKN_KELOMPOK C,KKN_ANGKATAN D, KKN_PERIODE E, KKN_TA F WHERE A.NO=B.NO AND B.ID_KELOMPOK=C.ID_KELOMPOK AND C.ID_ANGKATAN=D.ID_ANGKATAN AND D.ID_PERIODE=E.ID_PERIODE AND D.ID_TA=F.ID_TA AND A.NIM='$nim'");
		return $query;
	
	}
	
	function get_buktidaftar($nim){
		$query=$this->db->query("select DISTINCT A.NAMA_KELOMPOK, G.NAMA, C.NO, c.NIM,C.FAK, D.NM_DOSEN, D.MOBILE, A.RW ,A.DESA, E.NM_KEC, F.NM_KAB, I.ANGKATAN, J.PERIODE, K.TA FROM KKN_KELOMPOK A, KKN_DETAIL_KELOMPOK B, KKN_MHS C , D_DOSEN D, MD_KEC E, MD_KAB F, D_MAHASISWA G, KKN_KELOMPOK H, KKN_ANGKATAN I, KKN_PERIODE J, KKN_TA K WHERE A.ID_KELOMPOK=B.ID_KELOMPOK AND C.NO=B.NO AND A.KD_DOSEN=D.KD_DOSEN AND A.KD_KEC=E.KD_KEC AND A.KD_KAB=F.KD_KAB AND B.ID_KELOMPOK = H.ID_KELOMPOK AND H.ID_ANGKATAN= I.ID_ANGKATAN AND I.ID_PERIODE=J.ID_PERIODE AND J.ID_TA = K.ID_TA AND C.NIM=G.NIM AND C.NIM='$nim'");
		return $query;
	
	}

}
